tes/urls.py
from .views import SignupView, IndexView
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "tes"

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('media/<str:filepath>/', views.download_file),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

test1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tes.urls', namespace="tes")),
    path('accounts/', include('django.contrib.auth.urls')),
]

tes/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class ExcelModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    excelfile = models.FileField(upload_to='excel/', null=True, verbose_name="")

    def __str__(self):
        return self.pk
# Create your models here.

tes/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    email = forms.EmailField(label="Email")
    first_name = forms.CharField(label="Name")

    class Meta:
        model = User
        fields = ('email', 'first_name')

tes/views.py
import requests
from django.shortcuts import render, redirect, HttpResponse, Http404
import openpyxl
from .models import ExcelModel
from .forms import RegisterForm
from django.views.generic import TemplateView
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from django.contrib.auth import login
import mimetypes
from django.conf import settings
import os


class IndexView(TemplateView):
    template_name = 'tes/index.html'

    def get(self, request, *args, **kwargs):
        form = ExcelModel.objects.all()
        context = {
            'form': form
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        excel_file = request.FILES["excel_file"]
        wb = openpyxl.load_workbook(excel_file)
        worksheet = wb["Sheet1"]
        excel_data = list()
        count = 0
        i = 0
        for row in worksheet.iter_rows():
            i = i + 1
            row_data = list()
            for cell in row:
                row_data.append(str(cell.value))
            excel_data.append(row_data)
            if count == 0:
                worksheet.cell(row=i, column=2).value = "Latitude"
                worksheet.cell(row=i, column=3).value = "Longitude"
                count = count + 1
            else:
                api_key = "AIzaSyCZwboOYJ3h6qbHv1QUEcT-SN-yU2TPOlI"
                address = row_data
                api_response = requests.get(
                    'https://maps.googleapis.com/maps/api/geocode/json?address={0}&key={1}'.format(address, api_key))
                api_response_dict = api_response.json()
                if api_response_dict['status'] == 'OK':
                    latitude = api_response_dict['results'][0]['geometry']['location']['lat']
                    longitude = api_response_dict['results'][0]['geometry']['location']['lng']
                    worksheet.cell(row=i, column=2).value = str(latitude)
                    worksheet.cell(row=i, column=3).value = str(longitude)
                    wb.save(excel_file)
        form = ExcelModel()
        form.excelfile = excel_file
        form.user = request.user
        form.save()
        q = ExcelModel.objects.filter(user=request.user)
        context = {
            'excel_data': excel_data,
            'q': q
        }
        return render(request, self.template_name, context)


class SignupView(TemplateView):
    template_name = 'registration/signup.html'

    def get(self, request, *args, **kwargs):
        form = RegisterForm()
        context = {
            'form': form
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = User.objects.create(username=form.cleaned_data['email'],
                                       first_name=form.cleaned_data['first_name'],
                                       password=make_password(form.cleaned_data['password1']))
            login(request, user)
            return redirect('tes:index')
        context = {
            'form': form
        }
        return render(request, self.template_name, context)


def download_file(request, filepath):
    file_path = os.path.join(settings.MEDIA_ROOT, filepath)
    if os.path.exists(file_path):
        with open(file_path, 'rb') as fh:
            response = HttpResponse(fh.read(), content_type="application/vnd.ms-excel")
            response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_path)
            return response
    raise Http404

templates/base.html
{% load static %}

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <title>{% block title %} {% endblock %}</title>
        <style type="text/css">
            .asteriskField{
            display:none;
            }
        </style>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
            <div class="container">
                <a class="navbar-brand" href="{% url 'tes:index' %}">Excel Address Lookup</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                {% if user.is_authenticated %}
                    <ul class="navbar-nav ">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{ user.username }}
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'tes:index' %}">Home</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                            </div>
                        </li>
                    </ul>
                {% else %}
                    <form class="form-inline my-2 my-lg-0">
                        <a href="{% url 'login' %}" class="btn btn-outline-secondary"> Login </a>
                        <a href="{% url 'tes:signup' %}" class="btn btn-primary ml-2"> Signup </a>
                    </form>
                {% endif %}
            </div>
        </nav>
        <div class="container">

            {% block content %}
            {% endblock %}
            <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        </div>
    </body>
</html>

templates/tes/index.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
 <body style="background-color: #e8f3f7">
    <div class="col=6">
        <div class="Container" style="width:70%; background-color:#fff; border-radius:15px; padding-left: 50px; padding-right: 50px; padding-top:50px; margin-top: 50px; margin-bottom:50px; padding-bottom:50px">
                {% if user.is_authenticated %}
                    <h2>Welcome to Address Manager, {{ user.first_name }} !!!!</h2><br><br>
                    <h4> Upload Excel File</h4><br>
                    <form action="{% url 'tes:index' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="file" title="Upload excel file" name="excel_file" style="border: 1px solid black; padding: 5px;" required="required">
                        <p>
                            <input type="submit" value="Upload" class="btn btn-primary" style="border-radius: 5px; padding:5px; margin-top:10px; cursor: pointer;">
                    </form>
                    <hr>
                    <h4>Uploaded File Details:</h4>
                    {% for row in excel_data %}
                        {% for cell in row %}
                            {{ cell }}&nbsp;&nbsp;
                        {% endfor %}
                        <br>
                    {% endfor %}
                    <hr>
                    <h4>Download the files uploaded by {{ request.user.first_name }}</h4>
                    {% for e in q %}
                         <a href="/media/{{ e.excelfile }}/" class="btn btn-primary" style="border-radius: 5px; padding:5px; margin-top:10px; cursor: pointer; margin-left:5px;">Download file {{ e.pk }}</a>
                    {% endfor %}
                {% else %}
                    <h3>Signup for Address Locator !!!!</h3>
                    <ul>
                        <li>Upload Excel file with address.</li>
                        <li>App gets the longitude and latitude for it.</li>
                        <li>Download Excel Sheet with appended data.</li>
                    </ul>
                {% endif %}
        </div>
    </div>
</body>
{% endblock %}